[package]
name = "data-science"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
log = "0.4.27"
polars = { version = "0.48.1", features = ["lazy", "json"] }
reqwest = "0.12.19"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = "1.45.1"
